# Configure a course calendar
# Used for title of web page
courseTitle = "Classics 199, F'23"
# YYYY-MM-DD
firstDay = "2023-08-30"
lastDay = "2023-12-12"

# Pattern of class meetings: "mwf", "tt" or "wf"
schedule = "tth"

# Number of weeks the calendar should run for
totalWeeks =  15

fixedDates = [

  
  ["2023-10-05",  "Last class before fall break."],
  ["2023-10-17",  "Class resumes."],
  ["2023-11-21",  "Last class before Thanksgiving break."],
  ["2023-11-28",  "Class resumes."],
  ["2023-12-07",  "Last class."]
  
]